### ISSUE TITLE
Field prefixes

### ISSUE THREAD

**Issue by sammyd** [raywenderlich/java-style-guide#1]
The Android style guide recommends using `m` and `s` prefixes for member fields and static fields respectively.

This is of questionable use, and a lot of the wider Java community has decided to drop this convention, since IDEs will inform you of this kind of thing.

What should we do?

**Comment by ghost** [comment]
Personally I would lean towards doing as Google's style guide recommends, since all their sample and APIs will be written conforming to guide. It also states the same must be followed when contributing to Android itself.

**Comment by DarrylBayliss** [comment]
Agree with Mic. I eschew the Android conventions as much as anyone else, but I think for conformity's sake it's going to be good to stick with Googles style guide recommendations.

**Comment by sammyd** [comment]
It leaves a bad taste in my mouth, but I've updated the guide appropriately :mask: 

1a52182606504c29f7b2bc37126f2c72402871a5
