### ISSUE TITLE
Setters/Getters Preferred over public fields

### ISSUE THREAD

**Issue by sammyd** [raywenderlich/java-style-guide#3]
Pretty sure this is a standard Java rule. Do we have an opinion?

Even if a field is final?

**Comment by DarrylBayliss** [comment]
I think it's a safe bet to follow the standard. If a field is final then that says to me it's immutable so having getter/setters to access it may not make as much sense for the majority of cases.

**Comment by sammyd** [comment]
Given that there is a potential performance hit when dollowing this approach _internally_, do we want to specify this as a rule?

http://developer.android.com/training/articles/perf-tips.html#GettersSetters

Maybe we should see whether it is a problem first?

**Comment by DarrylBayliss** [comment]
I don't think it will be a problem for the size of our projects, as a general rule though if it's Google recommended we should probably roll with it. It's not going to add any more dev time moving your additional getter/setter functionality into a separate method that can be used throughout the whole class.

**Comment by sammyd** [comment]
Well, they recommend it for external access - but not internal.

The IDE will auto-generate loads of this guff. I'll try to capture this in the style guide

**Comment by DarrylBayliss** [comment]
Sorry. Should of been more explicit. Yes thats sounds right. :+1:

**Comment by sammyd** [comment]
Added a section https://github.com/raywenderlich/java-style-guide#getters--setters in adfb12e644cfc003c37cd4fa98fd61574c9d7656
