### ISSUE TITLE
Discourage Use of Enums

### ISSUE THREAD

**Issue by DarrylBayliss** [raywenderlich/java-style-guide#5]
I think it would be wise to discourage the use of Enums in Android in preference to Static Constants. The reasoning for this is because Google recommend using static constants instead of Enums in Android due to the increased memory they require.

http://developer.android.com/training/articles/memory.html#Overhead

**Comment by sammyd** [comment]
Updated the enums section in de02dbe6be380a52e664c40d3c7dae3ecf8b5e25
