### ISSUE TITLE
XML Styling

### ISSUE THREAD

**Issue by DarrylBayliss** [raywenderlich/java-style-guide#6]
Because XML is arguably just as important as Java on the Android system, I propose that we come up with some sort of convention that also falls in line with the guides governing attributes of  **conciseness**, **readability** and **simplicity**.

What I'm suggesting is based on a general look at how XML is declared for standard components/suggested names in Android Studio and looking at other similar guides on [GitHub](https://github.com/futurice/android-best-practices)
### **Prefix view based .xml files with the type of view they represent.**
- activity_login.xml
- fragment_main_screen.xml
- button_rounded_edges.xml
### **XML Indentation**

Indentation for elements should be kept to 2 characters
### **Keep style based XML attributes in the styles.xml file**

Unless there is good reason to deviate. All styling for your view components in your app should be done in the styles.xml file to keep style elements in one place.
### **Keep all strings in the strings.xml file**

Again unless there is good reason to deviate we should keep any strings in the app in strings.xml for quick availability.

Mostly likely other things and I hope others chime in.

**Comment by sammyd** [comment]
Do you also recommend colours in **colors.xml**? And some of the other resources? is **dimens.xml** standard? What other ones are there?

**Comment by sammyd** [comment]
At the moment I'm thinking that these guidelines should be incorporated _within_ the java style guide in a section dedicated to xml. That ok? If it is then I'll go ahead and make it.

**Comment by mluedke2** [comment]
@sammyd also **anim** and **drawable**. [list here](https://developer.android.com/guide/topics/resources/available-resources.html)

**Comment by mluedke2** [comment]
I like these. I would also add that we should consider setting a specific order for XML attributes, such as:
- `id` attribute
- `layout_*` attributes
- styling attributes such as `gravity` or `textColor`
- value attributes such as `text` or `src`

and then alphabetical within those four groups.

This makes it really easy to scan over layout xml and not have to search around every element. The exception I would make is if the tutorial specifically involves writing the attributes in a different order.

**Comment by DarrylBayliss** [comment]
I think colors/dimens.xml files are good to use as well. I think of it as CSS in a way. The style of a view should be abstracted away as much as possible unless there is a good reason not to. Same should go for content.

Totally agree with @mluedke2 about the order/alphabetical formatting for XML. I think the default formatter does this for you, so we should assume thats what Google wants us to adopt.

**Comment by sammyd** [comment]
I have added these suggestions to the guide. Please take a look at the new XML section, and if there are any problems then either PR or create a new issue.

Thanks guys :lollipop:
